<script lang="ts">
	import wasm, { Dictionary, Feedback } from "../../src-wasm/Cargo.toml";
  import {arrayEq} from "../etc/utils";
  
  // wordle table size
  const ROWS = 6;
  const COLS = 5;

  // regular expression for matching a letter
  const REG = /^[A-Z]$/;

  // need to make a ROW by COL matrix for the data table
  /** array corresponding to the rows of the wordle table. Each row is an array of 5 letters. */
  let content: string[][] = Array(ROWS).fill(0).map(()=>Array(COLS).fill(''));

  /** contains the feedback for previous guesses. */
  let feedback_arr: Feedback[][] = [];
  
  /** number of letters written down in the current row */
  let letter_nums = 0
  /** number of previous guesses, which also acts as an index into the current row. */
  let guesses = 0
  /** generated by web-assembly code. */
  let secret_word: string;
  
  // import wasm code
  let wasm_loaded = false;
  let wasm_exports: Dictionary | null = null;

  async function load() {
		wasm_exports = await wasm({});
    wasm_loaded = true;
    secret_word = wasm_exports.random_word();
    console.log(`[Game] The secret word is ${secret_word}`)
	}
	load();

  // function to remove a single letter
  function del_letter() {
    if (letter_nums > 0) {
      letter_nums--;
      content[guesses][letter_nums] = "";
    }
  }
  
  // Submit the currently written word.
  function submit_word(){
    if (guesses >= ROWS) {
      console.log(`[Game Error] The game is finished; There are ${ROWS} rows and you ahve guessed ${guesses} times`);
      return;
    } 
    
    if (letter_nums > COLS) {
      console.log(`[Game Error] Only ${letter_nums} letters written, needed ${COLS}`)
      return;
    }

    // turn the text into a lower-case word
    let guess: string = content[guesses].join("").toLowerCase();
    if (!wasm_exports.is_word(guess)) {
      console.log(`[Game Error] The entry ${guess} isn't a valid word.`)
      return;
    }

    // Often happens that js doesn't recognized true words.
    console.log(`[Game] ${guess} is a word`)

    // go back to the first column
    letter_nums = 0;
    guesses++;

    let feedback = wasm_exports.feedback(guess, secret_word)
    let human_feedback = feedback.map(el => {
      type FeedbackStr = "Not Found" | "Exact" | "Mismatch"
      let letter_feedback: FeedbackStr = "Not Found";
      switch (el) {
        case 0:
          letter_feedback =  "Not Found"
          break;
        case 1:
          letter_feedback =  "Exact"
          break
        case 2:
          letter_feedback = "Mismatch"
          break
      }
      return letter_feedback
    })
    
    console.log(`[Game] The feedback is ${human_feedback}.`)

    if (arrayEq(feedback, [1, 1, 1, 1, 1])) {
      console.log("[Game] You win!")
    } else {
      
    }

    feedback_arr.push(feedback);
    feedback_arr = feedback_arr;
    
  }


  function try_read_key(ev) {
    let key = ev.key.toUpperCase();
    if (REG.test(key) && letter_nums < COLS) {
      content[guesses][letter_nums] = key;
      letter_nums++;
    }
  }

  function handle_key(ev) { 
    // match the keycode
    switch (ev.keyCode) {
      case 8: {
        /* backspace */
        del_letter()
        break;
      }
      case 13: {
        /* enter */

        // submitting a word requires wasm code
        if(!wasm_loaded) {
          console.log("Ignoring keystroke as WASM has not loaded yet.")
          return;
        }
        submit_word()
        break
      }
      default: {
        /* Try to read a key */
        try_read_key(ev)
      }
    }
  }
</script>

<svelte:window on:keydown={handle_key}/>

<h1>GAME</h1>
<table>
  {#each content as row, i}
    <tr>
      {#each row as col, j}
      <td 
        class:green= "{feedback_arr?.[i]?.[j] == 1}"
        class:yellow= "{feedback_arr?.[i]?.[j] == 2}"
        class:red= "{feedback_arr?.[i]?.[j] == 0}"  
      >
        <span class:active="{i == guesses && j == letter_nums - 1}">
          {col}
        </span>
      </td>
      {/each}
    </tr>
  {/each}
</table>

<style>
  .active {
    color: gold;
  }
  .green {
    background-color: rgb(170, 226, 86);
  }
  .red {
    background-color: rgb(192, 27, 63);
  }
  .yellow {
    background-color: rgb(220, 235, 20);
  }
  table {
    margin-left: auto;
    margin-right: auto;
  }
  td {
    background-color: cornsilk;
    width: 3em;
    height: 3em;
  }
  span {
    background-color: transparent;
    font-size: 2em;
    color: black;
    font-weight: bold;
  }
</style>